import { log } from "../helpers/helpers";
import { Mode } from "..";
import { readFileSync } from "fs";
import { RootFolders, DirMap, FileMap, SceneMap } from "./scan";

const helpText = `
'encode' will receive a path to the project structure generated by 'scan'
 and encode files by its extension.
 the output will be a .h strip.`

 let vflag:boolean = false

 const encoders:Encoder[] = [
    {extension: ".lvcode", npm_module: "lv-encoder-lvcode"},
    {extension: ".lvsprite", npm_module: "lv-encoder-sprite"},
 ]
 
 export interface Encoder {
    extension:string
    npm_module:string
 }

 export interface Encoded {
     rom_data:string
     declaration:string
     on_enter:string
     on_exit:string
     on_frame:string
 }

export function encode(input:string, output:string, mode:Mode) {
    if (mode == "help") log(true, helpText)
    else {

        vflag = mode == "verbose" ? true : false
        log(vflag, "[command] encode")

        const jsonString = readFileSync(input, "utf8")
        const data:RootFolders = JSON.parse(jsonString) 
        
        data.scenes.forEach( scene => {
            encodeScene(scene)
        })
    }
} 

function encodeScene(scene:SceneMap) {
    log(vflag, "encoding: " + scene.name)
    encodeDir(scene, scene)
}

function encodeDir(dir:DirMap, scene:SceneMap) {
    dir.directories.forEach( dir =>  encodeDir(dir, scene))
    dir.files.forEach( file => encodeFile(file, scene))
}

function encodeFile(file:FileMap, scene:SceneMap) {
    encoders.forEach( encoder => {
        if (encoder.extension == file.extension) {
            log(vflag, "encoding file: " + file.name + " with " + encoder.npm_module)
        }
    })
}