import { log } from "../helpers/helpers";
import { Mode } from "..";

const helpText = `
'encode' will receive a path to the project structure generated by 'scan'
 and encode files by its extension.
 the output will be a .h strip.`

export function encode(input:string, output:string, mode:Mode) {
    
} 