import { projectContent } from ".."
import { log } from "../helpers/helpers"
import { mode } from "../index";

const helpText = `
'reduce' will receive a path to the encoded files generated by 'encode'
 and merge all files into the C++ source files, ready to be compiled.`

 export let vflag:boolean = false
 export let outputDir:string
 export let project:projectContent

 export async function reduce(input:string, output:string, mode:mode) {
    if (mode == "help") log(true, helpText)
    else {

    }
}