"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const helpers_1 = require("../helpers/helpers");
const helpText = `
'reduce' will receive a path to the encoded files generated by 'encode'
 and merge all files into the C++ source files, ready to be compiled.`;
exports.vflag = false;
function reduce(input, output, mode) {
    return __awaiter(this, void 0, void 0, function* () {
        if (mode == "help")
            helpers_1.log(true, helpText);
        else {
        }
    });
}
exports.reduce = reduce;
